import { useEffect, useRef } from 'react';
import { WalletAnalysis } from '../types';

interface WalletCardProps {
  data: WalletAnalysis;
}

export function WalletCard({ data }: WalletCardProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    if (canvasRef.current) {
      drawCard(canvasRef.current, data);
    }
  }, [data]);

  const downloadImage = () => {
    if (canvasRef.current) {
      const link = document.createElement('a');
      link.download = `solana-card-${data.address.slice(0, 8)}.png`;
      link.href = canvasRef.current.toDataURL();
      link.click();
    }
  };

  return (
    <div>
      <div className="canvas-container">
        <canvas ref={canvasRef} width={1200} height={630} />
      </div>
      <button className="btn download-btn" onClick={downloadImage}>
        Download Card
      </button>
    </div>
  );
}

function drawCard(canvas: HTMLCanvasElement, data: WalletAnalysis) {
  const ctx = canvas.getContext('2d');
  if (!ctx) return;

  const width = canvas.width;
  const height = canvas.height;

  // Background gradient
  const gradient = ctx.createLinearGradient(0, 0, width, height);
  gradient.addColorStop(0, '#0a0a0f');
  gradient.addColorStop(0.5, '#14141f');
  gradient.addColorStop(1, '#1a1a2e');
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, width, height);

  // Add accent gradient overlay
  const accentGradient = ctx.createLinearGradient(0, 0, width, height);
  accentGradient.addColorStop(0, 'rgba(153, 69, 255, 0.1)');
  accentGradient.addColorStop(1, 'rgba(20, 241, 149, 0.1)');
  ctx.fillStyle = accentGradient;
  ctx.fillRect(0, 0, width, height);

  // Border
  ctx.strokeStyle = '#2a2a3e';
  ctx.lineWidth = 4;
  ctx.strokeRect(10, 10, width - 20, height - 20);

  // Title
  ctx.fillStyle = '#ffffff';
  ctx.font = 'bold 48px Arial';
  ctx.fillText('SOLANA WALLET CARD', 60, 80);

  // Address
  ctx.fillStyle = '#a0a0b0';
  ctx.font = '24px monospace';
  const shortAddress = `${data.address.slice(0, 8)}...${data.address.slice(-8)}`;
  ctx.fillText(shortAddress, 60, 120);

  // Whale Status - Large and prominent
  const tierColors: Record<string, string> = {
    Kraken: '#ff0080',
    Whale: '#9945ff',
    Shark: '#14f195',
    Dolphin: '#4da6ff',
    Fish: '#ffd700',
  };

  const tierColor = tierColors[data.whaleStatus.tier] || '#14f195';

  // Whale tier circle background
  ctx.fillStyle = 'rgba(153, 69, 255, 0.2)';
  ctx.beginPath();
  ctx.arc(width - 200, 150, 100, 0, Math.PI * 2);
  ctx.fill();

  // Whale tier text
  ctx.fillStyle = tierColor;
  ctx.font = 'bold 36px Arial';
  ctx.textAlign = 'center';
  ctx.fillText(data.whaleStatus.tier, width - 200, 145);

  ctx.fillStyle = '#ffffff';
  ctx.font = '20px Arial';
  ctx.fillText(`${data.whaleStatus.solBalance.toFixed(2)} SOL`, width - 200, 175);
  ctx.textAlign = 'left';

  // Stats Section
  let yPos = 200;

  // OG Status
  drawStatBox(ctx, 60, yPos, 500, 120, 'OG STATUS',
    data.ogStatus.daysSinceFirst !== null
      ? `${data.ogStatus.daysSinceFirst} days on Solana`
      : 'No history',
    '#9945ff'
  );

  // Last Seen
  drawStatBox(ctx, 640, yPos, 500, 120, 'LAST SEEN',
    data.lastSeen.daysSinceLast !== null
      ? data.lastSeen.daysSinceLast === 0
        ? 'Active today'
        : `${data.lastSeen.daysSinceLast} days ago`
      : 'No activity',
    '#14f195'
  );

  yPos += 150;

  // Top Holdings
  drawStatBox(ctx, 60, yPos, 500, 200, 'TOP HOLDINGS',
    data.topHoldings.slice(0, 4).map(h =>
      `${h.symbol}: ${h.amount.toFixed(2)}`
    ).join('\n'),
    '#4da6ff'
  );

  // Top Ecosystems
  drawStatBox(ctx, 640, yPos, 500, 200, 'TOP ECOSYSTEMS',
    data.topEcosystems.length > 0
      ? data.topEcosystems.map(e =>
          `${e.name}: ${e.interactionCount} txns`
        ).join('\n')
      : 'No ecosystem interactions',
    '#ffd700'
  );

  // Footer
  ctx.fillStyle = '#a0a0b0';
  ctx.font = '18px Arial';
  ctx.textAlign = 'center';
  ctx.fillText('Generated by Solana Card', width / 2, height - 30);
  ctx.textAlign = 'left';
}

function drawStatBox(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  width: number,
  height: number,
  label: string,
  value: string,
  accentColor: string
) {
  // Box background
  ctx.fillStyle = 'rgba(26, 26, 46, 0.8)';
  ctx.fillRect(x, y, width, height);

  // Border with accent color
  ctx.strokeStyle = accentColor;
  ctx.lineWidth = 2;
  ctx.strokeRect(x, y, width, height);

  // Label
  ctx.fillStyle = accentColor;
  ctx.font = 'bold 20px Arial';
  ctx.fillText(label, x + 20, y + 35);

  // Value
  ctx.fillStyle = '#ffffff';
  ctx.font = '24px Arial';

  const lines = value.split('\n');
  lines.forEach((line, index) => {
    ctx.fillText(line, x + 20, y + 75 + (index * 32));
  });
}
